package com.oplus.camera.aps.util;

/* loaded from: classes2.dex */
public class CameraApsExifData {
    public java.lang.String mDocExifGpsDateStamp;
    public com.oplus.exif.OplusRational[] mDocExifGpsTimeStamp;
    public com.oplus.exif.OplusRational mExifAltitude;
    public int mExifAltitudeRef;
    public com.oplus.exif.OplusRational mExifAperture;
    public com.oplus.exif.OplusRational mExifBrightness;
    public int mExifColorSpace;
    public java.lang.String mExifComments;
    public java.lang.String mExifComponentsConfig;
    public java.lang.String mExifDateTime;
    public com.oplus.exif.OplusRational mExifExpTime;
    public com.oplus.exif.OplusRational mExifExposureBias;
    public int mExifExposureMode;
    public int mExifExposureProgram;
    public com.oplus.exif.OplusRational mExifFNumber;
    public java.lang.String mExifFlashPixVersion;
    public com.oplus.exif.OplusRational mExifFocalLength;
    public int mExifFocalLength35Mm;
    public long mExifIso;
    public com.oplus.exif.OplusRational[] mExifLatitude;
    public java.lang.String mExifLatitudeRef;
    public com.oplus.exif.OplusRational[] mExifLongitude;
    public java.lang.String mExifLongitudeRef;
    public java.lang.String mExifMakerNote;
    public java.lang.String mExifManufacture;
    public com.oplus.exif.OplusRational mExifMaxAperture;
    public int mExifMeteringMode;
    public java.lang.String mExifModel;
    public int mExifRotate;
    public int mExifSceneCaptureType;
    public java.lang.String mExifSceneType;
    public int mExifSensingMethod;
    public com.oplus.exif.OplusRational mExifShutterSpeed;
    public java.lang.String mExifSubDateTime;
    public java.lang.String mExifVersion;
    public int mExifWhiteBalanceMode;
    public int mFlashValue;
    public int mHeicQuality;
    public int mImageHeight;
    public int mImageWidth;
    public java.lang.String mInteropIndexStr;
    public java.lang.String mInteropVersion;
    public java.lang.String mSensorName;
    public int mTiffResolutionUnit;
    public com.oplus.exif.OplusRational mTiffXResolution;
    public com.oplus.exif.OplusRational mTiffYResolution;
    public int mTiffYcrcbPositioning;
    public boolean mbMirror;
    public boolean mbSupportDCIP3;
    public boolean mbSupportLocation;
    public boolean mbSupportLocationTimeStamp;

    public CameraApsExifData(com.oplus.ocs.camera.CameraPictureCallback.CameraPictureResult cameraPictureResult) {
        this.mExifLatitude = new com.oplus.exif.OplusRational[3];
        this.mExifLongitude = new com.oplus.exif.OplusRational[3];
        this.mDocExifGpsTimeStamp = new com.oplus.exif.OplusRational[3];
        if (cameraPictureResult == null || cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_IMAGE_WIDTH) == null) {
            return;
        }
        this.mSensorName = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SENSOR_NAME);
        this.mExifRotate = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_ROTATE)).intValue();
        this.mExifIso = ((java.lang.Long) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_ISO)).longValue();
        this.mExifWhiteBalanceMode = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_WHITE_BALANCE_MODE)).intValue();
        this.mFlashValue = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_FLASH_VALUE)).intValue();
        this.mExifLatitudeRef = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_LATITUDE_REF);
        this.mExifLongitudeRef = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_LONGITUDE_REF);
        this.mExifAltitudeRef = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_ALTITUDE_REF)).intValue();
        this.mDocExifGpsDateStamp = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_GPS_DATE_STAMP);
        this.mExifDateTime = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_DATE_TIME);
        this.mExifSubDateTime = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SUB_DATE_TIME);
        this.mExifModel = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_MODEL);
        this.mExifManufacture = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_MANUFACTURE);
        this.mExifComments = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_COMMENTS);
        this.mbMirror = ((java.lang.Boolean) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_MIRROR)).booleanValue();
        this.mExifFNumber = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_NUMBER);
        this.mExifExpTime = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_EXP_TIME);
        this.mExifAperture = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_APERTURE);
        this.mExifExposureBias = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_EXPOSURE_BIAS);
        this.mExifFocalLength = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_FOCAL_LENGTH);
        this.mExifLatitude = (com.oplus.exif.OplusRational[]) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_LATITUDE);
        this.mExifLongitude = (com.oplus.exif.OplusRational[]) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_LONGITUDE);
        this.mExifAltitude = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_ALTITUDE);
        this.mDocExifGpsTimeStamp = (com.oplus.exif.OplusRational[]) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_GPS_TIME_STAMP);
        this.mbSupportDCIP3 = ((java.lang.Boolean) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SUPPORT_DCIP3)).booleanValue();
        this.mbSupportLocation = ((java.lang.Boolean) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SUPPORT_LOCATION)).booleanValue();
        this.mbSupportLocationTimeStamp = ((java.lang.Boolean) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SUPPORT_LOCATION_TIME_STAMP)).booleanValue();
        this.mImageWidth = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_IMAGE_WIDTH)).intValue();
        this.mImageHeight = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_IMAGE_HEIGHT)).intValue();
        this.mTiffYcrcbPositioning = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_TIFFYCRCB_POSITIONING)).intValue();
        this.mTiffResolutionUnit = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_TIFF_RESOLUTION_UNIT)).intValue();
        this.mTiffXResolution = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_TIFFX_RESOLUTIION);
        this.mTiffYResolution = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_TIFFY_RESOLUTION);
        this.mExifExposureProgram = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_EXPOSURE_PROGRAM)).intValue();
        this.mExifVersion = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_VERSION);
        this.mExifComponentsConfig = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_COMPONENT_CONFIG);
        this.mExifShutterSpeed = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SHUTTER_SPEED);
        this.mExifBrightness = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_BRIGHTNESS);
        this.mExifMaxAperture = (com.oplus.exif.OplusRational) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_MAX_APERTURE);
        this.mExifMeteringMode = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_METERING_MODE)).intValue();
        this.mExifMakerNote = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_MAKER_NOTE);
        this.mExifFlashPixVersion = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_FLASH_PIX_VERSION);
        this.mExifColorSpace = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_COLOR_SPACE)).intValue();
        this.mExifSensingMethod = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SENSING_METHOD)).intValue();
        this.mExifSceneType = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SCENE_TYPE);
        this.mExifExposureMode = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_EXPOSURE_MODE)).intValue();
        this.mExifFocalLength35Mm = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_FOCAL_LENGTH_35MM)).intValue();
        this.mExifSceneCaptureType = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_SCENE_CAPTURE_TYPE)).intValue();
        this.mInteropIndexStr = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_INTEROP_INDEX_STR);
        this.mInteropVersion = (java.lang.String) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_INTEROP_VERSION);
        this.mHeicQuality = ((java.lang.Integer) cameraPictureResult.get(com.oplus.ocs.camera.CameraParameter.EXIF_HEIC_QUALITY)).intValue();
    }
}
