package com.oplus.camera.aps.util;

import com.oplus.exif.OplusRational;
import com.oplus.ocs.camera.CameraParameter;
import com.oplus.ocs.camera.CameraPictureCallback;

/* loaded from: classes2.dex */
public class CameraApsExifData {
    public String mDocExifGpsDateStamp;
    public OplusRational[] mDocExifGpsTimeStamp;
    public OplusRational mExifAltitude;
    public int mExifAltitudeRef;
    public OplusRational mExifAperture;
    public OplusRational mExifBrightness;
    public int mExifColorSpace;
    public String mExifComments;
    public String mExifComponentsConfig;
    public String mExifDateTime;
    public OplusRational mExifExpTime;
    public OplusRational mExifExposureBias;
    public int mExifExposureMode;
    public int mExifExposureProgram;
    public OplusRational mExifFNumber;
    public String mExifFlashPixVersion;
    public OplusRational mExifFocalLength;
    public int mExifFocalLength35Mm;
    public long mExifIso;
    public OplusRational[] mExifLatitude;
    public String mExifLatitudeRef;
    public OplusRational[] mExifLongitude;
    public String mExifLongitudeRef;
    public String mExifMakerNote;
    public String mExifManufacture;
    public OplusRational mExifMaxAperture;
    public int mExifMeteringMode;
    public String mExifModel;
    public int mExifRotate;
    public int mExifSceneCaptureType;
    public String mExifSceneType;
    public int mExifSensingMethod;
    public OplusRational mExifShutterSpeed;
    public String mExifSubDateTime;
    public String mExifVersion;
    public int mExifWhiteBalanceMode;
    public int mFlashValue;
    public int mHeicQuality;
    public int mImageHeight;
    public int mImageWidth;
    public String mInteropIndexStr;
    public String mInteropVersion;
    public String mSensorName;
    public int mTiffResolutionUnit;
    public OplusRational mTiffXResolution;
    public OplusRational mTiffYResolution;
    public int mTiffYcrcbPositioning;
    public boolean mbMirror;
    public boolean mbSupportDCIP3;
    public boolean mbSupportLocation;
    public boolean mbSupportLocationTimeStamp;

    public CameraApsExifData(CameraPictureCallback.CameraPictureResult cameraPictureResult) {
        this.mExifLatitude = new OplusRational[3];
        this.mExifLongitude = new OplusRational[3];
        this.mDocExifGpsTimeStamp = new OplusRational[3];
        if (cameraPictureResult == null || cameraPictureResult.get(CameraParameter.EXIF_IMAGE_WIDTH) == null) {
            return;
        }
        this.mSensorName = (String) cameraPictureResult.get(CameraParameter.EXIF_SENSOR_NAME);
        this.mExifRotate = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_ROTATE)).intValue();
        this.mExifIso = ((Long) cameraPictureResult.get(CameraParameter.EXIF_ISO)).longValue();
        this.mExifWhiteBalanceMode = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_WHITE_BALANCE_MODE)).intValue();
        this.mFlashValue = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_FLASH_VALUE)).intValue();
        this.mExifLatitudeRef = (String) cameraPictureResult.get(CameraParameter.EXIF_LATITUDE_REF);
        this.mExifLongitudeRef = (String) cameraPictureResult.get(CameraParameter.EXIF_LONGITUDE_REF);
        this.mExifAltitudeRef = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_ALTITUDE_REF)).intValue();
        this.mDocExifGpsDateStamp = (String) cameraPictureResult.get(CameraParameter.EXIF_GPS_DATE_STAMP);
        this.mExifDateTime = (String) cameraPictureResult.get(CameraParameter.EXIF_DATE_TIME);
        this.mExifSubDateTime = (String) cameraPictureResult.get(CameraParameter.EXIF_SUB_DATE_TIME);
        this.mExifModel = (String) cameraPictureResult.get(CameraParameter.EXIF_MODEL);
        this.mExifManufacture = (String) cameraPictureResult.get(CameraParameter.EXIF_MANUFACTURE);
        this.mExifComments = (String) cameraPictureResult.get(CameraParameter.EXIF_COMMENTS);
        this.mbMirror = ((Boolean) cameraPictureResult.get(CameraParameter.EXIF_MIRROR)).booleanValue();
        this.mExifFNumber = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_NUMBER);
        this.mExifExpTime = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_EXP_TIME);
        this.mExifAperture = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_APERTURE);
        this.mExifExposureBias = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_EXPOSURE_BIAS);
        this.mExifFocalLength = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_FOCAL_LENGTH);
        this.mExifLatitude = (OplusRational[]) cameraPictureResult.get(CameraParameter.EXIF_LATITUDE);
        this.mExifLongitude = (OplusRational[]) cameraPictureResult.get(CameraParameter.EXIF_LONGITUDE);
        this.mExifAltitude = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_ALTITUDE);
        this.mDocExifGpsTimeStamp = (OplusRational[]) cameraPictureResult.get(CameraParameter.EXIF_GPS_TIME_STAMP);
        this.mbSupportDCIP3 = ((Boolean) cameraPictureResult.get(CameraParameter.EXIF_SUPPORT_DCIP3)).booleanValue();
        this.mbSupportLocation = ((Boolean) cameraPictureResult.get(CameraParameter.EXIF_SUPPORT_LOCATION)).booleanValue();
        this.mbSupportLocationTimeStamp = ((Boolean) cameraPictureResult.get(CameraParameter.EXIF_SUPPORT_LOCATION_TIME_STAMP)).booleanValue();
        this.mImageWidth = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_IMAGE_WIDTH)).intValue();
        this.mImageHeight = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_IMAGE_HEIGHT)).intValue();
        this.mTiffYcrcbPositioning = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_TIFFYCRCB_POSITIONING)).intValue();
        this.mTiffResolutionUnit = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_TIFF_RESOLUTION_UNIT)).intValue();
        this.mTiffXResolution = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_TIFFX_RESOLUTIION);
        this.mTiffYResolution = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_TIFFY_RESOLUTION);
        this.mExifExposureProgram = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_EXPOSURE_PROGRAM)).intValue();
        this.mExifVersion = (String) cameraPictureResult.get(CameraParameter.EXIF_VERSION);
        this.mExifComponentsConfig = (String) cameraPictureResult.get(CameraParameter.EXIF_COMPONENT_CONFIG);
        this.mExifShutterSpeed = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_SHUTTER_SPEED);
        this.mExifBrightness = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_BRIGHTNESS);
        this.mExifMaxAperture = (OplusRational) cameraPictureResult.get(CameraParameter.EXIF_MAX_APERTURE);
        this.mExifMeteringMode = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_METERING_MODE)).intValue();
        this.mExifMakerNote = (String) cameraPictureResult.get(CameraParameter.EXIF_MAKER_NOTE);
        this.mExifFlashPixVersion = (String) cameraPictureResult.get(CameraParameter.EXIF_FLASH_PIX_VERSION);
        this.mExifColorSpace = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_COLOR_SPACE)).intValue();
        this.mExifSensingMethod = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_SENSING_METHOD)).intValue();
        this.mExifSceneType = (String) cameraPictureResult.get(CameraParameter.EXIF_SCENE_TYPE);
        this.mExifExposureMode = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_EXPOSURE_MODE)).intValue();
        this.mExifFocalLength35Mm = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_FOCAL_LENGTH_35MM)).intValue();
        this.mExifSceneCaptureType = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_SCENE_CAPTURE_TYPE)).intValue();
        this.mInteropIndexStr = (String) cameraPictureResult.get(CameraParameter.EXIF_INTEROP_INDEX_STR);
        this.mInteropVersion = (String) cameraPictureResult.get(CameraParameter.EXIF_INTEROP_VERSION);
        this.mHeicQuality = ((Integer) cameraPictureResult.get(CameraParameter.EXIF_HEIC_QUALITY)).intValue();
    }
}
