package com.oplus.camera.statistics.model;

/* loaded from: classes2.dex */
public class VideoRecordMsgData extends com.oplus.camera.statistics.model.DcsMsgData {
    public static final java.lang.String END_TYPE_MOMORY_LIMIT = "memory_limit";
    public static final java.lang.String END_TYPE_NORMAL = "normal";
    public static final java.lang.String END_TYPE_TEMP_COUNT_DOWN_TO_STOP = "count_down_to_stop";
    public static final java.lang.String END_TYPE_TEMP_LIMIT = "temp_limit";
    public static final java.lang.String EVENT_PAUSE = "pause";
    public static final java.lang.String EVENT_VIDEO_RECORD = "videoRecord";
    private static final java.lang.String KEY_10BITS_HEIC_ENCODE = "10bit_image_value";
    private static final java.lang.String KEY_AE_AF_LOCK = "ae_af_lock";
    private static final java.lang.String KEY_AI_ENHANCE_CHANGE = "ai_enhance_change";
    private static final java.lang.String KEY_AI_ENHANCE_END = "ai_enhance_end";
    private static final java.lang.String KEY_AI_ENHANCE_START = "ai_enhance_start";
    private static final java.lang.String KEY_AVAILABLE_STORAGE = "available_storage";
    public static final java.lang.String KEY_BEFORE_PAUSE_DURATION = "before_pause_duration";
    private static final java.lang.String KEY_CCT = "cct_value";
    private static final java.lang.String KEY_END_TYPE = "end_type";
    private static final java.lang.String KEY_EXP = "exp_value";
    private static final java.lang.String KEY_FACE_COUNT = "face_count";
    private static final java.lang.String KEY_FACE_COUNT_START = "face_count_start";
    private static final java.lang.String KEY_FILE_PATH = "file_path";
    private static final java.lang.String KEY_FLASH_MODE = "flash_mode";
    private static final java.lang.String KEY_FUNC_SLOGAN_LOCATE = "slogan_locate";
    private static final java.lang.String KEY_FUNC_SLOGAN_SIZE = "slogan_size";
    private static final java.lang.String KEY_HIGH_BRIGHTNESS = "screen_highlight";
    public static final java.lang.String KEY_HOLDING_TIME = "holding_time";
    private static final java.lang.String KEY_HORIZONTAL_OR_VERTICAL = "horizontal_or_vertical";
    private static final java.lang.String KEY_ISO = "iso_value";
    private static final java.lang.String KEY_IS_AI_ENHANCE = "is_ai_enhance";
    private static final java.lang.String KEY_IS_ASSISTANT_LINE = "is_assistant_line";
    private static final java.lang.String KEY_IS_CUSTOM_SLOGAN = "is_custom_slogan";
    private static final java.lang.String KEY_IS_LOCATION_SLOGAN = "is_location_slogan";
    private static final java.lang.String KEY_IS_MODEL_SLOGAN = "is_model_slogan";
    private static final java.lang.String KEY_IS_MOTION_FASTVIDEO = "is_motion_fastVideo";
    private static final java.lang.String KEY_IS_NIGHT_SCENE = "is_night_scene";
    private static final java.lang.String KEY_IS_OVERLAP = "is_overlap";
    private static final java.lang.String KEY_IS_RECORD_LOCATION = "is_record_location";
    private static final java.lang.String KEY_IS_SD_CARD = "is_sd";
    private static final java.lang.String KEY_IS_SHUTTER_VOICE = "is_shutter_voice";
    private static final java.lang.String KEY_IS_STABLIZED = "is_stablized";
    private static final java.lang.String KEY_IS_TIME_SLOGAN = "is_time_slogan";
    private static final java.lang.String KEY_IS_VIDEO_3HDR = "hdr_mode";
    private static final java.lang.String KEY_IS_WIDE_ANGLE = "is_wide_angle";
    private static final java.lang.String KEY_LOCATION = "location";
    public static final java.lang.String KEY_LOCKING_TIME = "locking_time";
    private static final java.lang.String KEY_LUX = "lux_value";
    private static final java.lang.String KEY_MEMORY_VALUE = "memory_value";
    private static final java.lang.String KEY_MOVIE_CAMERA_ID = "movie_camera_id";
    private static final java.lang.String KEY_MOVIE_EV_VALUE = "movie_ev_value";
    private static final java.lang.String KEY_MOVIE_EXP_TIME = "movie_exp_time";
    private static final java.lang.String KEY_MOVIE_FOCUS_VALUE = "movie_focus_value";
    private static final java.lang.String KEY_MOVIE_HDR_MODE = "movie_hdr_mode";
    private static final java.lang.String KEY_MOVIE_HISTOGRAM_MODE = "histogram_mode";
    private static final java.lang.String KEY_MOVIE_ISO_VALUE = "movie_iso_value";
    private static final java.lang.String KEY_MOVIE_LOG_MODE = "log_value";
    private static final java.lang.String KEY_MOVIE_STEADY = "movie_steady";
    private static final java.lang.String KEY_MOVIE_WB_VALUE = "movie_wb_value";
    private static final java.lang.String KEY_ORIENTATION_START = "orientation_start";
    public static final java.lang.String KEY_PAUSE_CLICK_TIMES = "times";
    private static final java.lang.String KEY_PIC_SIZE_TYPE = "pic_size_type";
    private static final java.lang.String KEY_POSTERIZE_TIME = "posterize_time";
    private static final java.lang.String KEY_PREVIEW_CAPTURE_COST_TIME = "preview_capture_cost_time";
    private static final java.lang.String KEY_PROTOCOL_VERSION = "protocol_version";
    private static final java.lang.String KEY_RECORDING_END_TEMPERATURE = "recording_end_temperature";
    private static final java.lang.String KEY_RECORDING_START_TEMPERATURE = "recording_start_temperature";
    private static final java.lang.String KEY_SCREEN_COMPOSE = "screen_compose";
    private static final java.lang.String KEY_SCREEN_MODE = "screen_mode";
    private static final java.lang.String KEY_SHUTTER_TYPE = "capture_type";
    private static final java.lang.String KEY_SLOW_VIDEO_DRAG_BOX = "drag_box";
    private static final java.lang.String KEY_SLOW_VIDEO_INTELLI_DETECT = "intelli_detect";
    private static final java.lang.String KEY_SPIRIT_LEVEL = "spirit_level";
    private static final java.lang.String KEY_STICKER_NAME = "sticker_name";
    private static final java.lang.String KEY_STICKER_TYPE = "sticker_type";
    private static final java.lang.String KEY_STICKER_UUID = "sticker_uuid";
    private static final java.lang.String KEY_TOUCH_EXPOSURE_COMPENSATION = "touch_ev";
    private static final java.lang.String KEY_TOUCH_XY = "touchxy_value";
    private static final java.lang.String KEY_TOUCH_XY_HYPER_LPASE_VIEW = "hyper_lapse_focus_view";
    private static final java.lang.String KEY_ULTRA_STEADY = "ultra_steady";
    private static final java.lang.String KEY_VIDEO_ASSISTANT_LINE = "video_assistant_line";
    private static final java.lang.String KEY_VIDEO_BLUR_START_FACE_COUNT = "face_count_start";
    private static final java.lang.String KEY_VIDEO_BLUR_START_ORIENTATION = "orientation_start";
    private static final java.lang.String KEY_VIDEO_CODEC = "video_codec";
    public static final java.lang.String KEY_VIDEO_DB_EFFECT_VALUE_MIXED = "mixed";
    public static final java.lang.String KEY_VIDEO_DB_EFFECT_VALUE_SILHOUETTE = "silhouette";
    private static final java.lang.String KEY_VIDEO_DB_EXPO_EFFECT = "db_expo_effect";
    private static final java.lang.String KEY_VIDEO_DEWIND_NOISE = "wnr_trigger";
    private static final java.lang.String KEY_VIDEO_FACE_BEAUTY = "video_face_beauty";
    private static final java.lang.String KEY_VIDEO_FPS = "video_fps";
    private static final java.lang.String KEY_VIDEO_GENERATE_TIME = "generate_time";
    private static final java.lang.String KEY_VIDEO_MODE = "video_mode";
    private static final java.lang.String KEY_VIDEO_RECORDER_SOUND = "video_recorder_sound";
    private static final java.lang.String KEY_VIDEO_SIZE_TYPE = "video_rec_mode";
    private static final java.lang.String KEY_VIDEO_TIME = "video_time";
    private static final java.lang.String KEY_VOLUME_FUNCTION = "volume_function";
    private static final java.lang.String REGEX_FOCUS = "^0\\.\\d_renamed*[1-9]\\d_renamed*|0|1|auto$";
    private static final java.lang.String REGEX_ISO = "^0|([1-9][0-9]*)|auto$";
    private static final java.lang.String REGEX_WB = "^([2-8][0-9]00)|auto$";
    private static final java.lang.String TAG = "VideoRecordMsgData";
    public java.lang.String m10BitsEncode;
    public java.lang.String mAeAfLock;
    public int mAiEnhanceSceneChangeCount;
    public int mAiEnhanceSceneEnd;
    public int mAiEnhanceSceneStart;
    public long mAvaliableStorage;
    public long mBeforePauseDuration;
    public java.lang.String mCct;
    public java.lang.String mDoubleExposureEffect;
    public java.lang.String mEndType;
    public java.lang.String mExp;
    public int mFaceCount;
    public java.lang.String mFilePath;
    public java.lang.String mFlashMode;
    public long mGenerateTime;
    public long mHoldingTime;
    public java.lang.String mHorizontalOrVertical;
    public java.lang.String mIs3HDR;
    public java.lang.String mIsAiEnhance;
    public java.lang.String mIsAssistantLine;
    public java.lang.String mIsCustomSlogan;
    public java.lang.String mIsDragBox;
    public java.lang.String mIsHistogramOpen;
    public java.lang.String mIsIntelligentDetect;
    public java.lang.String mIsLocationSlogan;
    public java.lang.String mIsLog;
    public java.lang.String mIsModelSlogan;
    public java.lang.String mIsMovieHdr;
    public java.lang.String mIsNightScene;
    public java.lang.String mIsOverlap;
    public java.lang.String mIsRecordLocation;
    public java.lang.String mIsSDCard;
    public java.lang.String mIsShutterVoice;
    public java.lang.String mIsStablized;
    public java.lang.String mIsTimeSlogan;
    public java.lang.String mIsWideAngle;
    public java.lang.String mIso;
    public java.lang.String mLocation;
    public long mLockingTime;
    public java.lang.String mLux;
    public java.lang.String mMemoryValue;
    public java.lang.String mMotionFastVideo;
    public java.lang.String mMovieCameraId;
    public java.lang.String mMovieEvValue;
    public java.lang.String mMovieExpTime;
    public java.lang.String mMovieFocusValue;
    public java.lang.String mMovieIsoValue;
    public java.lang.String mMovieSteady;
    public java.lang.String mMovieWbValue;
    public java.lang.String mNoiseFilter;
    public long mPauseTimes;
    public java.lang.String mPicSizeType;
    public java.lang.String mPosterizeTime;
    public long mPreviewCaptureCostTime;
    public java.lang.String mProtocolVersion;
    public java.lang.String mRecordingEndTemperature;
    public java.lang.String mRecordingStartTemperature;
    public java.lang.String mScreenCompose;
    public java.lang.String mScreenMode;
    public java.lang.String mShutterType;
    public java.lang.String mSloganLocate;
    public java.lang.String mSloganSize;
    public java.lang.String mSpiritLevel;
    public int mStartVideoRecordingFaceCount;
    public int mStartVideoRecordingOrientation;
    public java.lang.String mStickerName;
    public java.lang.String mStickerType;
    public java.lang.String mStickerUuid;
    public java.lang.String mSubScreenValue;
    public java.lang.String mTouchEVValue;
    public java.lang.String mTouchXYMotionFastVideo;
    public java.lang.String mTouchXYValue;
    public java.lang.String mUltraSteady;
    public java.lang.String mVideoAssistantLine;
    public java.lang.String mVideoCodec;
    public int mVideoFaceBeauty;
    public java.lang.String mVideoFps;
    public java.lang.String mVideoMode;
    public java.lang.String mVideoRecorderSound;
    public java.lang.String mVideoSizeType;
    public long mVideoTime;
    public java.lang.String mVolumeFunction;

    public VideoRecordMsgData(android.content.Context context) {
        super(context, com.oplus.camera.statistics.model.DcsMsgData.LOGTAG_VIDEO, "videoRecord");
        this.mVideoTime = 0L;
        this.mGenerateTime = 0L;
        this.mPauseTimes = 0L;
        this.mBeforePauseDuration = 0L;
        this.mHoldingTime = 0L;
        this.mLockingTime = 0L;
        this.mVideoMode = "";
        this.mVideoSizeType = "";
        this.mVideoFps = "";
        this.mFlashMode = "";
        this.mAvaliableStorage = 0L;
        this.mVideoCodec = "";
        this.mVideoRecorderSound = "";
        this.mNoiseFilter = "";
        this.mPreviewCaptureCostTime = 0L;
        this.mVideoFaceBeauty = 0;
        this.mStartVideoRecordingOrientation = 0;
        this.mStartVideoRecordingFaceCount = 0;
        this.mTouchEVValue = "";
        this.mTouchXYValue = "";
        this.mFaceCount = 0;
        this.mLocation = "";
        this.mVolumeFunction = "";
        this.mIsShutterVoice = "";
        this.mAeAfLock = "";
        this.mIsCustomSlogan = "";
        this.mIsLocationSlogan = "";
        this.mIsModelSlogan = "";
        this.mIsTimeSlogan = "";
        this.mIsRecordLocation = "";
        this.mIsStablized = "";
        this.mUltraSteady = "";
        this.m10BitsEncode = "";
        this.mMemoryValue = "";
        this.mFilePath = "";
        this.mShutterType = "";
        this.mStickerName = "";
        this.mStickerType = "";
        this.mStickerUuid = "";
        this.mProtocolVersion = "";
        this.mIsWideAngle = "";
        this.mIs3HDR = "";
        this.mIsNightScene = "";
        this.mIsAiEnhance = "";
        this.mLux = "";
        this.mEndType = "";
        this.mRecordingStartTemperature = "";
        this.mRecordingEndTemperature = "";
        this.mMotionFastVideo = "";
        this.mTouchXYMotionFastVideo = "";
        this.mPosterizeTime = "";
        this.mExp = "";
        this.mIso = "";
        this.mCct = "";
        this.mSpiritLevel = "";
        this.mVideoAssistantLine = "";
        this.mHorizontalOrVertical = "";
        this.mIsOverlap = "";
        this.mSubScreenValue = "";
        this.mScreenCompose = "";
        this.mScreenMode = "";
        this.mIsSDCard = "";
        this.mIsIntelligentDetect = "";
        this.mIsDragBox = "";
        this.mPicSizeType = "";
        this.mMovieCameraId = "";
        this.mMovieSteady = "";
        this.mMovieExpTime = "";
        this.mMovieIsoValue = "";
        this.mMovieFocusValue = "";
        this.mMovieEvValue = "";
        this.mMovieWbValue = "";
        this.mIsAssistantLine = "";
        this.mIsHistogramOpen = "";
        this.mIsLog = "";
        this.mIsMovieHdr = "";
        this.mDoubleExposureEffect = "";
        this.mSloganLocate = "";
        this.mSloganSize = "";
        this.mAiEnhanceSceneStart = 0;
        this.mAiEnhanceSceneEnd = 0;
        this.mAiEnhanceSceneChangeCount = 0;
    }

    public void buildEvent(boolean z_renamed) {
        this.mEventId = z_renamed ? EVENT_PAUSE : "videoRecord";
    }

    @Override // com.oplus.camera.statistics.model.DcsMsgData
    public void report() {
        if (!android.text.TextUtils.isEmpty(this.mCaptureMode) && com.oplus.camera.aps.constant.ApsConstant.CAPTURE_MODE_STICKER.equals(this.mCaptureMode)) {
            this.mCaptureType = 2;
        }
        prepareLogTagByCaptureType();
        checkEmptyCondition("ae_af_lock", java.lang.String.valueOf(this.mAeAfLock));
        checkGreatCondition("available_storage", this.mAvaliableStorage, -1);
        checkNoAnyCondition("face_count", java.lang.String.valueOf(this.mFaceCount));
        checkNoAnyCondition("face_count_start", java.lang.String.valueOf(this.mStartVideoRecordingFaceCount));
        checkEmptyCondition(KEY_FILE_PATH, this.mFilePath);
        checkEmptyCondition(KEY_FLASH_MODE, this.mFlashMode);
        checkEmptyCondition(KEY_IS_CUSTOM_SLOGAN, this.mIsCustomSlogan);
        checkEmptyCondition(KEY_IS_LOCATION_SLOGAN, this.mIsLocationSlogan);
        checkEmptyCondition(KEY_IS_MODEL_SLOGAN, this.mIsModelSlogan);
        checkEmptyCondition(KEY_IS_RECORD_LOCATION, this.mIsRecordLocation);
        checkEmptyCondition(KEY_IS_SHUTTER_VOICE, this.mIsShutterVoice);
        checkEmptyCondition(KEY_IS_STABLIZED, this.mIsStablized);
        checkEmptyCondition(KEY_IS_TIME_SLOGAN, this.mIsTimeSlogan);
        checkEmptyCondition("location", this.mLocation);
        checkEmptyCondition(KEY_IS_WIDE_ANGLE, this.mIsWideAngle);
        checkEmptyCondition(KEY_MEMORY_VALUE, this.mMemoryValue);
        checkEmptyCondition("orientation_start", java.lang.String.valueOf(this.mStartVideoRecordingOrientation));
        checkGreatCondition("preview_capture_cost_time", this.mPreviewCaptureCostTime, -1);
        checkEmptyCondition(KEY_PROTOCOL_VERSION, this.mProtocolVersion);
        checkEmptyCondition("capture_type", this.mShutterType);
        checkEmptyCondition("sticker_name", this.mStickerName);
        checkEmptyCondition("sticker_type", this.mStickerType);
        checkEmptyCondition("sticker_uuid", this.mStickerUuid);
        checkEmptyCondition(KEY_TOUCH_XY, this.mTouchXYValue);
        checkNoAnyCondition("touch_ev", this.mTouchEVValue);
        checkEmptyCondition(KEY_ULTRA_STEADY, this.mUltraSteady);
        checkEmptyCondition(KEY_10BITS_HEIC_ENCODE, this.m10BitsEncode);
        checkEmptyCondition("video_codec", this.mVideoCodec);
        checkEmptyCondition(KEY_VIDEO_DEWIND_NOISE, this.mNoiseFilter);
        checkEmptyCondition("video_fps", this.mVideoFps);
        checkEmptyCondition("video_mode", this.mVideoMode);
        checkEmptyCondition("video_rec_mode", this.mVideoSizeType);
        checkGreatCondition("video_time", this.mVideoTime, 0);
        checkGreatCondition(KEY_VIDEO_GENERATE_TIME, this.mVideoTime, 0);
        checkEmptyCondition("video_recorder_sound", this.mVideoRecorderSound);
        checkEmptyCondition("volume_function", this.mVolumeFunction);
        checkEmptyCondition(KEY_IS_VIDEO_3HDR, this.mIs3HDR);
        checkEmptyCondition(KEY_IS_NIGHT_SCENE, this.mIsNightScene);
        checkEmptyCondition(KEY_IS_AI_ENHANCE, this.mIsAiEnhance);
        checkNoAnyCondition("lux_value", this.mLux);
        checkEmptyCondition(KEY_END_TYPE, this.mEndType);
        checkEmptyCondition(KEY_RECORDING_START_TEMPERATURE, this.mRecordingStartTemperature);
        checkEmptyCondition(KEY_RECORDING_END_TEMPERATURE, this.mRecordingEndTemperature);
        checkEmptyCondition(KEY_IS_MOTION_FASTVIDEO, this.mMotionFastVideo);
        checkEmptyCondition(KEY_POSTERIZE_TIME, this.mPosterizeTime);
        checkGreatCondition(KEY_VIDEO_GENERATE_TIME, this.mGenerateTime, 0);
        checkEmptyCondition(KEY_TOUCH_XY_HYPER_LPASE_VIEW, this.mTouchXYMotionFastVideo);
        checkEmptyCondition("cct_value", this.mCct);
        checkEmptyCondition("exp_value", this.mExp);
        checkEmptyCondition("iso_value", this.mIso);
        checkEmptyCondition(KEY_SPIRIT_LEVEL, this.mSpiritLevel);
        checkEmptyCondition(KEY_VIDEO_ASSISTANT_LINE, this.mVideoAssistantLine);
        checkEmptyCondition(KEY_HORIZONTAL_OR_VERTICAL, this.mHorizontalOrVertical);
        checkEmptyCondition(KEY_IS_OVERLAP, this.mIsOverlap);
        checkEmptyCondition("subscreen_value", this.mSubScreenValue);
        checkEmptyCondition(KEY_SCREEN_COMPOSE, this.mScreenCompose);
        checkEmptyCondition(KEY_SCREEN_MODE, this.mScreenMode);
        checkEmptyCondition(KEY_IS_SD_CARD, this.mIsSDCard);
        checkEmptyCondition(KEY_SLOW_VIDEO_INTELLI_DETECT, this.mIsIntelligentDetect);
        checkEmptyCondition(KEY_SLOW_VIDEO_DRAG_BOX, this.mIsDragBox);
        checkEmptyCondition(KEY_PIC_SIZE_TYPE, this.mPicSizeType);
        checkEmptyCondition(KEY_MOVIE_CAMERA_ID, this.mMovieCameraId);
        checkEmptyCondition(KEY_IS_ASSISTANT_LINE, this.mIsAssistantLine);
        checkEmptyCondition(KEY_MOVIE_EXP_TIME, this.mMovieExpTime);
        checkEmptyCondition(KEY_MOVIE_EV_VALUE, this.mMovieEvValue);
        checkEmptyCondition("video_mode", this.mVideoMode);
        checkEmptyCondition(KEY_MOVIE_STEADY, this.mMovieSteady);
        checkEmptyCondition(KEY_MOVIE_HISTOGRAM_MODE, this.mIsHistogramOpen);
        checkEmptyCondition(KEY_MOVIE_LOG_MODE, this.mIsLog);
        checkEmptyCondition(KEY_MOVIE_HDR_MODE, this.mIsMovieHdr);
        checkGreatCondition(KEY_AI_ENHANCE_START, this.mAiEnhanceSceneStart, 0);
        checkGreatCondition(KEY_AI_ENHANCE_END, this.mAiEnhanceSceneEnd, 0);
        checkGreatCondition(KEY_AI_ENHANCE_CHANGE, this.mAiEnhanceSceneChangeCount, 0);
        checkGreatCondition(KEY_PAUSE_CLICK_TIMES, this.mPauseTimes, 0);
        checkGreatCondition(KEY_BEFORE_PAUSE_DURATION, this.mBeforePauseDuration, 0);
        checkGreatCondition(KEY_HOLDING_TIME, this.mHoldingTime, 0);
        checkGreatCondition(KEY_LOCKING_TIME, this.mLockingTime, 0);
        checkEmptyCondition("db_expo_effect", this.mDoubleExposureEffect);
        checkEmptyCondition(KEY_FUNC_SLOGAN_LOCATE, this.mSloganLocate);
        checkEmptyCondition(KEY_FUNC_SLOGAN_SIZE, this.mSloganSize);
        if (java.util.regex.Pattern.matches(REGEX_ISO, this.mMovieIsoValue)) {
            checkEmptyCondition(KEY_MOVIE_ISO_VALUE, this.mMovieIsoValue);
        }
        if (java.util.regex.Pattern.matches(REGEX_FOCUS, this.mMovieFocusValue)) {
            checkEmptyCondition(KEY_MOVIE_FOCUS_VALUE, this.mMovieFocusValue);
        }
        if (java.util.regex.Pattern.matches(REGEX_WB, this.mMovieWbValue)) {
            checkEmptyCondition(KEY_MOVIE_WB_VALUE, this.mMovieWbValue);
        }
        if (com.oplus.camera.aps.constant.ApsConstant.REC_MODE_COMMON.equals(this.mVideoMode) || com.oplus.camera.aps.constant.ApsConstant.CAPTURE_MODE_STICKER.equals(this.mVideoMode)) {
            checkNoAnyCondition("orientation_start", java.lang.String.valueOf(this.mStartVideoRecordingOrientation));
            checkNoAnyCondition("face_count_start", java.lang.String.valueOf(this.mStartVideoRecordingFaceCount));
        }
        if (this.mSmooth == 102) {
            checkGreatCondition("video_face_beauty", this.mSmoothDermabrasion, -1);
            checkGreatCondition(com.oplus.camera.statistics.model.DcsMsgData.KEY_SMOOTH_FACE_LEAN, this.mSmoothFaceLean, -1);
            checkGreatCondition(com.oplus.camera.statistics.model.DcsMsgData.KEY_SMOOTH_EYE_BIG, this.mSmoothEyeBig, -1);
            checkGreatCondition(com.oplus.camera.statistics.model.DcsMsgData.KEY_SMOOTH_NOSE_LEAN, this.mSmoothNoseLean, -1);
            checkGreatCondition(com.oplus.camera.statistics.model.DcsMsgData.KEY_SMOOTH_FACE_JAW, this.mSmoothFaceJaw, -51);
            checkGreatCondition(com.oplus.camera.statistics.model.DcsMsgData.KEY_SMOOTH_FACE_SMALL, this.mSmoothFaceSmall, -1);
            checkGreatCondition(com.oplus.camera.statistics.model.DcsMsgData.KEY_SMOOTH_FRESHEN_UP, this.mSmoothFreshenUp, -1);
            checkGreatCondition(com.oplus.camera.statistics.model.DcsMsgData.KEY_SMOOTH_CUBE, this.mSmoothCube, -1);
        }
        super.report();
    }
}
