package com.oplus.camera.aps.config;

/* loaded from: classes2.dex */
public class CameraFunction {
    public static final java.lang.String AIS_SNAPSHOT = "func_ais_snapshot";
    public static final java.lang.String AI_ENHANCEMENT_VIDEO = "func_enhancement_video";
    public static final java.lang.String APS_BRACKETMODE = "func_aps_bracketmode";
    public static final java.lang.String BLUR_NOT_SUPPORT_EXPLORER = "func_blur_not_support_explorer";
    public static final java.lang.String BOKEH = "func_bokeh";
    public static final java.lang.String CACHE_CLICK_CAPTURE = "func_cache_click_capture";
    public static final java.lang.String DERED_EYE = "func_dered_eye";
    public static final java.lang.String DOUBLE_EXPOSURE = "func_video_double_exposure";
    public static final java.lang.String FACE_BEAUTY_COMMON = "func_face_beauty_common";
    public static final java.lang.String FACE_BEAUTY_CUSTOM = "func_face_beauty_custom";
    public static final int FACE_BEAUTY_FLAG = 0;
    public static final java.lang.String FACE_BEAUTY_PROCESS = "func_face_beauty_process";
    public static final java.lang.String FACE_BLUR = "func_face_blur";
    public static final java.lang.String FACE_SLENDER_PROCESS = "func_face_slender_process";
    public static final int FILTER_FLAG = 1;
    public static final java.lang.String FILTER_VIGNETTE = "func_filter_vignette";
    public static final java.lang.String FISH_EYE = "fish_eye";
    public static final java.lang.String GOOGLE_LENS = "func_google_lens";
    public static final java.lang.String ID_PHOTO = "func_id_photo";
    public static final java.lang.String IOT_CAPTURE = "func_iot_capture";
    public static final java.lang.String KEY_VIDEO_HYPER_LAPSE_PROCESS = "func_video_hyper_lapse_process";
    public static final java.lang.String KEY_VIDEO_SUPER_EIS_PROCESS = "func_video_super_eis_process";
    public static final java.lang.String KEY_VIDEO_SUPER_EIS_WIDE = "func_video_super_eis_wide";
    public static final java.lang.String LONG_EXPOSURE = "func_long_exposure";
    public static final int MASK_FLAG = 255;
    public static final java.lang.String MODE_PANEL = "func_mode_panel";
    public static final java.lang.String MOVIE_MODE_V2 = "func_movie_mode_v2";
    public static final java.lang.String OUT_CAPTURE_CLOSE_ENABLE = "func_out_capture_close_enable";
    public static final java.lang.String OUT_CAPTURE_ENABLE = "func_out_capture";
    public static final java.lang.String OUT_PREVIEW_BUTTON_SHOW = "func_out_preview_button_show";
    public static final java.lang.String OUT_PREVIEW_CAPTURE_ENABLE = "func_out_preview_capture";
    public static final java.lang.String OUT_PREVIEW_ENABLE = "func_out_preview";
    public static final java.lang.String PF_V3 = "func_pf_v3";
    public static final java.lang.String RAW_HDR = "key_raw_hdr";
    public static final java.lang.String REQUEST_FAST_LAUNCH = "func_request_fast_launch";
    public static final java.lang.String RESET_AUTO_FOCUS = "func_reset_auto_focus";
    public static final java.lang.String SAT_CAMERA = "func_sat_camera";
    public static final java.lang.String SCALE_PREVIEW = "func_scale_preview";
    public static final java.lang.String SUPER_TEXT = "func_super_text";
    public static final java.lang.String SUPER_TEXT_CPU_PROCESS = "func_super_text_cpu_process";
    public static final java.lang.String SUPER_TEXT_GPU_PROCESS = "func_super_text_gpu_process";
    public static final java.lang.String TILT_SHIFT = "func_tilt_shift";
    public static final java.lang.String TORCH_SOFT_LIGHT = "func_torch_soft_light";
    public static final java.lang.String ULTRA_NIGHT_VIDEO = "func_ultra_night_video";
    public static final java.lang.String VIDEO_BLUR_PROCESS = "func_video_blur_process";
    public static final java.lang.String VIDEO_HDR = "func_hdr";
    public static final java.lang.String VIDEO_RETENTION = "func_video_retention";
}
